### PR TITLE
Support setting UI Test target application

### PR DESCRIPTION
**Pull request by plu**
When using UI Tests, Xcode is building some UI Test Runner Application behind the scenes. This application includes the XCTest target. When Xcode is executing the tests, it actually runs this application. When loading the XCTest bundle it will launch the "real" application during the test run. This is usually done by overriding `setUp` and calling `XCUIApplication().launch()`.

To support this in the framework two more properties need to be set on `XCTestConfiguration`:

* `targetApplicationPath`
* `targetApplicationBundleID`

### CODE REVIEW

**Comment by plu** [comment]
This is good to go 👍 .

**Comment by lawrencelomax** [comment]
This lgtm, but I have some changes pending for some of the classes you are changing. It would make most sense to merge this after I commit those changes.

**Comment by plu** [comment]
Sure, just land yours first, then I will rebase and adapt.

**Comment by plu** [comment]
Adapted to latest changes from `master` and ready to go 👍 .

**Comment by plu** [comment]
I just noticed some changes in the headers in the Beta:

```diff
+@property(copy) NSArray *targetApplicationArguments; // @synthesize targetApplicationArguments=_targetApplicationArguments;
+@property(copy) NSDictionary *targetApplicationEnvironment; // @synthesize targetApplicationEnvironment=_targetApplicationEnvironment;
```

But I will make a separate pull request for that once this one was merged.

**Comment by lawrencelomax** [comment]
This has changed a lot since when this PR was first up.

@plu if you want to dust this off again I'd be happy to see if it's still relevant

**Comment by plu** [comment]
Not relevant anymore, thanks for asking! You can also close my other PR's or tickets.

**Pull request closed without merging**
