### PR TITLE
Allowing to specify existing files for stdin/stdout

### PR DESCRIPTION
**Pull request by mikelikespie**
This is useful if wanting to redirect stdout to a pseudoterminal

### CODE REVIEW

**Comment by mikelikespie** [comment]
@facebook-github-bot I work for Square, Inc. and I believe we have a corporate CLA

**Comment by lawrencelomax** [comment]
@mikelikespie Can you send an email to cla@fb.ocm please? I can see that you have a number of colleagues at Square who have signed the cla but you aren't showing up on the tool. Thanks!

**Comment by lawrencelomax** [comment]
@mikelikespie I'd be happy to land this, but the bot is not showing your username as CLA-signed.

**Comment by mikelikespie** [comment]
Hmmm. I actually work at FB now (mrl@) Sorry dropped the ball on this like a year ago. I’m pretty sure before there was a CLA signed with square for whom I worked when I wrote this

**Comment by lawrencelomax** [comment]
Welcome!

**Pull request closed without merging**
